name: GitHub-Profile-Summary-Cards

on:
  schedule: # 毎週月曜日の0時0分に実行
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.README }}
        with:
          USERNAME: ${{ github.repository_owner }}
